---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: roar-web
  name: roar-web
  namespace: roar
spec:
  ports:
  - name: frontend
    port: 8089
    targetPort: 8080
  selector:
    app: roar-web
  type: NodePort
